### ISSUE TITLE
ImportError: cannot import name 'Dialect' from 'sqlalchemy' (M:\SD\sdwebui\py310\lib\site-packages\sqlalchemy\__init__.py)

### ISSUE THREAD

**Issue by swumagic** [ArtVentureX/sd-webui-agent-scheduler#113]
sd-webui-agent-scheduler
*** Error loading script: task_scheduler.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 19, in <module>
        from agent_scheduler.task_runner import (
      File "M:\SD\sdwebui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 24, in <module>
        from .db import TaskStatus, Task, task_manager
      File "M:\SD\sdwebui\extensions\sd-webui-agent-scheduler\agent_scheduler\db\__init__.py", line 6, in <module>
        from .task import TaskStatus, Task, TaskManager
      File "M:\SD\sdwebui\extensions\sd-webui-agent-scheduler\agent_scheduler\db\task.py", line 5, in <module>
        from sqlalchemy import (
    ImportError: cannot import name 'Dialect' from 'sqlalchemy' (M:\SD\sdwebui\py310\lib\site-packages\sqlalchemy\__init__.py)

**Comment by artventuredev** [comment]
This should be fixed with the latest commit, please give it a try.
