### ISSUE TITLE
Scheduler broken

### ISSUE THREAD

**Issue by MadSilence88** [ArtVentureX/sd-webui-agent-scheduler#17]
The latest update of SD-Webui wont work correctly with task Scheduler. The tasks are scheduled, and run, but the tab Task Scheduler has no DB entries that you can pause or resume. It just queues them up and works in the background. I also get some errors starting up.

Traceback (most recent call last):
  File "C:\StableDiffusion\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\StableDiffusion\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\StableDiffusion\extensions\sd-webui-agent-scheduler\scripts\api.py", line 8, in <module>
    from scripts.db import TaskStatus, task_manager
ImportError: cannot import name 'TaskStatus' from 'scripts.db' (unknown location)

Error loading script: task_runner.py
Traceback (most recent call last):
  File "C:\StableDiffusion\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\StableDiffusion\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\StableDiffusion\extensions\sd-webui-agent-scheduler\scripts\task_runner.py", line 22, in <module>
    from scripts.db import TaskStatus, Task, task_manager
ImportError: cannot import name 'TaskStatus' from 'scripts.db' (unknown location)

Error loading script: task_scheduler.py
Traceback (most recent call last):
  File "C:\StableDiffusion\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\StableDiffusion\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\StableDiffusion\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 7, in <module>
    from scripts.task_runner import TaskRunner, get_instance
  File "C:\StableDiffusion\extensions\sd-webui-agent-scheduler\scripts\task_runner.py", line 22, in <module>
    from scripts.db import TaskStatus, Task, task_manager
ImportError: cannot import name 'TaskStatus' from 'scripts.db' (unknown location)

**Comment by artventurdev** [comment]
@MadSilence88 Please update the latest version of the extension and check if the issue still happen. I tried both latest versions from A1111 and Vlad version and the extension still work correctly.

**Comment by MadSilence88** [comment]
I did that, this is the latest version on all. extensions etc. tested on 2 systems. :S

**Comment by artventurdev** [comment]
@MadSilence88  I have an M1 macOS and an windows 11 both are still working.

Please add the following snippet to the top of the `sd-webui-agent-scheduler\scripts\api.py` file and observe the output log.

```python
import sys
print("============= debug sys path", sys.path)
```

Also please navigate to `sd-webui-agent-scheduler\scripts` and `sd-webui-agent-scheduler\scripts\db` and capture the file list.

These output may help me investigate further, right now I have no clue about what could be the cause.
