### ISSUE TITLE
秋叶整合包，点击排队按钮，然后进到插件页面就看到任务失败了

### ISSUE THREAD

**Issue by luzhouchen816** [ArtVentureX/sd-webui-agent-scheduler#177]
---
ERROR:sd:[AgentScheduler] Task 5465a4af-bc30-4995-983d-e35242988712 failed: 
*** Error completing request
*** Arguments: ('task(ugnwzshkrzoc129)', '{best quality}, {{masterpiece}}, {highres}, extremely detailed CG, extremely detailed 8K wallpaper, extremely detailed character, {an extremely delicate and beautiful}, portrait, illustration, solo focus, straight-on, dramatic angle, depthoffield, {{cinematiclighting}}, outdoors, {{{character({{{a girl}}}, solo, loli, {{{{full body}}}}, standing, expressionless, [[[light smile]]], cute, beautiful detailed eyes, blue eyes, [long legs], {very_long_hair}, blonde hair, wavy_hair, [shiny hair], {{Gothic_Lolita}}, blue_white skirt, {{short skirt}}, black_Headdress, bowknot, {{{hair ornament}}}, [hair flower], stocking, [[Garter]], Lace, cross-laced footwear, ribbon-trimmed sleeves)}}}, [background(building architecture, {{gothic architecture}}, starry sky, outdoors, church, {castle}, [[fantasy]])]', '', [], 20, 'Euler a', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', ['Clip skip: 2', 'Model hash: 二次元\\暗系插画风-darkSushiMixMix_colorful.safetensors [969673ad74]', 'VAE: vae-ft-mse-840000-ema-pruned.safetensors'], <agent_scheduler.task_runner.FakeRequest object at 0x00000290192DCA30>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, True, False, False, False, 'base', False, False, {}, {}, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 960, 64, True, True, True, False, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', {'is_cnet': True, 'enabled': False, 'module': 'none', 'model': 'None', 'weight': 1.0, 'image': None, 'resize_mode': 'Crop and Resize', 'low_vram': False, 'processor_res': -1, 'threshold_a': -1, 'threshold_b': -1, 'guidance_start': 0.0, 'guidance_end': 1.0, 'pixel_perfect': False, 'control_mode': 'Balanced', 'save_detected_map': True, 'is_ui': True, 'input_mode': 'simple', 'batch_images': None, 'output_dir': '', 'loopback': False}, {'is_cnet': True, 'enabled': False, 'module': 'none', 'model': 'None', 'weight': 1.0, 'image': None, 'resize_mode': 'Crop and Resize', 'low_vram': False, 'processor_res': -1, 'threshold_a': -1, 'threshold_b': -1, 'guidance_start': 0.0, 'guidance_end': 1.0, 'pixel_perfect': False, 'control_mode': 'Balanced', 'save_detected_map': True, 'is_ui': True, 'input_mode': 'simple', 'batch_images': None, 'output_dir': '', 'loopback': False}, {'is_cnet': True, 'enabled': False, 'module': 'none', 'model': 'None', 'weight': 1.0, 'image': None, 'resize_mode': 'Crop and Resize', 'low_vram': False, 'processor_res': -1, 'threshold_a': -1, 'threshold_b': -1, 'guidance_start': 0.0, 'guidance_end': 1.0, 'pixel_perfect': False, 'control_mode': 'Balanced', 'save_detected_map': True, 'is_ui': True, 'input_mode': 'simple', 'batch_images': None, 'output_dir': '', 'loopback': False}, {'is_cnet': True, 'enabled': False, 'module': 'none', 'model': 'None', 'weight': 1, 'image': None, 'resize_mode': 'Crop and Resize', 'low_vram': False, 'processor_res': -1, 'threshold_a': -1, 'threshold_b': -1, 'guidance_start': 0, 'guidance_end': 1, 'pixel_perfect': False, 'control_mode': 'Balanced', 'save_detected_map': True, 'is_ui': True, 'input_mode': 'simple', 'batch_images': '', 'output_dir': '', 'loopback': False}, False, '', 0.5, True, False, '', 'Lerp', False, '🔄', False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "D:\A-sd\sd-webui-aki-v4.3\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\A-sd\sd-webui-aki-v4.3\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "D:\A-sd\sd-webui-aki-v4.3\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "D:\A-sd\sd-webui-aki-v4.3\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 39, in processing_process_images_hijack
        cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)
      File "D:\A-sd\sd-webui-aki-v4.3\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 184, in get_cn_batches
        units = external_code.get_all_units_in_processing(p)
      File "D:\A-sd\sd-webui-aki-v4.3\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 191, in get_all_units_in_processing
        return get_all_units(p.scripts, p.script_args)
      File "D:\A-sd\sd-webui-aki-v4.3\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 202, in get_all_units
        return get_all_units_from(script_args[cn_script.args_from:cn_script.args_to])
      File "D:\A-sd\sd-webui-aki-v4.3\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 233, in get_all_units_from
        all_units = [
      File "D:\A-sd\sd-webui-aki-v4.3\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 234, in <listcomp>
        to_processing_unit(script_arg)
      File "D:\A-sd\sd-webui-aki-v4.3\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 307, in to_processing_unit
        unit = ControlNetUnit(**unit)
    TypeError: ControlNetUnit.__init__() got an unexpected keyword argument 'is_cnet'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
ERROR:sd:[AgentScheduler] Task c0045f5f-1df8-411f-a453-66a4daffcd7a failed:

**Comment by artventuredev** [comment]
Please update the extension to the latest version. This issue is already fixed.

**Comment by luzhouchen816** [comment]
非常感谢，已经成功运行了
