### ISSUE TITLE
和 sd-webui-EasyPhoto 这个插件冲突，有这个插件会添加不进去队列，我关掉该插件就好了。

### ISSUE THREAD

**Issue by luzhouchen816** [ArtVentureX/sd-webui-agent-scheduler#178]
Traceback (most recent call last):
  File "D:\AI-sd\sd-webui-aki-v4.3\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI-sd\sd-webui-aki-v4.3\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\AI-sd\sd-webui-aki-v4.3\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI-sd\sd-webui-aki-v4.3\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI-sd\sd-webui-aki-v4.3\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AI-sd\sd-webui-aki-v4.3\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\AI-sd\sd-webui-aki-v4.3\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI-sd\sd-webui-aki-v4.3\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 218, in f
    task_runner.register_ui_task(
  File "D:\AI-sd\sd-webui-aki-v4.3\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 275, in register_ui_task
    (params, script_args) = self.__serialize_ui_task_args(
  File "D:\AI-sd\sd-webui-aki-v4.3\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 128, in __serialize_ui_task_args
    script_params = serialize_script_args(script_args)
  File "D:\AI-sd\sd-webui-aki-v4.3\extensions\sd-webui-agent-scheduler\agent_scheduler\task_helpers.py", line 197, in serialize_script_args
    return zlib.compress(pickle.dumps(script_args))
_pickle.PicklingError: Can't pickle <class 'animatediff_utils.py.AnimateDiffProcess'>: import of module 'animatediff_utils.py' failed

**Comment by coderCK2** [comment]
I encountered this issue as well. Installing EasyPhoto breaks Agent Scheduler. In the end, I removed EasyPhoto, and Agent Scheduler started working again.
