### ISSUE TITLE
ValueError: 'ResizeMode.INNER_FIT' is not a valid ResizeMode

### ISSUE THREAD

**Issue by bankkomin** [ArtVentureX/sd-webui-agent-scheduler#192]
Exception in thread Thread-57 (execute_task):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\bankk\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 332, in execute_task
    task_args = self.parse_task_args(task)
  File "C:\Users\bankk\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 243, in parse_task_args
    named_args, script_args = self.__deserialize_ui_task_args(
  File "C:\Users\bankk\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 191, in __deserialize_ui_task_args
    script_args = deserialize_script_args(script_args, self.UiControlNetUnit)
  File "C:\Users\bankk\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_helpers.py", line 211, in deserialize_script_args
    unit[k] = type(getattr(u, k))(v)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'ResizeMode.INNER_FIT' is not a valid ResizeMode

**Comment by ASCII-S** [comment]
same error

**Comment by iainsyme** [comment]
im seeing this too on a Mac install. its happened twice after wiping extensions and rebuilding - seemingly randomly whilst im between prompts.
