### ISSUE TITLE
Doesn't display scheluded tasks

### ISSUE THREAD

**Issue by ultrazebra** [ArtVentureX/sd-webui-agent-scheduler#195]
Used to work in the past, now seems to be broken in the latest A1111 version.
It still scheludes tasks, but doesn't display anything in the list.
Browser log:
```
file=script.js?1702735346.265253:85 error running callback ƒ n(){if(gradioApp().querySelector("#agent_scheduler_tabs")==null){setTimeout(n,500);return}xu||(Rw(),Ow(),Tw(),Pw(),xu=!0)} : TypeError: Cannot read properties of null (reading 'childElementCount')
    at Rw (agent-scheduler.iife.js?1702742428.543969:302:9714)
    at n (agent-scheduler.iife.js?1702742428.543969:330:1954)
    at executeCallbacks (file=script.js?1702735346.265253:83:13)
    at MutationObserver.<anonymous> (file=script.js?1702735346.265253:109:13)
```
![scheluder](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/56080895/d304da16-5e64-4a23-b770-ad0a83c9a525)

**Comment by MIDG3Tp3nguin** [comment]
Has also stopped working for me as well since latest A1111 update.

I get this error in console;

```
*** Error running after_component: C:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py
    Traceback (most recent call last):
      File "C:\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 800, in after_component
        script.after_component(component, **kwargs)
      File "C:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 111, in after_component
        toprow.add(self.enqueue_row)
    AttributeError: 'NoneType' object has no attribute 'add'

---
Creating model from config: C:\Automatic1111\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
*** Error running after_component: C:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py
    Traceback (most recent call last):
      File "C:\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 800, in after_component
        script.after_component(component, **kwargs)
      File "C:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 111, in after_component
        toprow.add(self.enqueue_row)
    AttributeError: 'NoneType' object has no attribute 'add'

---
```

**Comment by hotwareboy** [comment]
Same issue.  Agent scheduler works fine with master a1111 branch.  Broken on dev branch.  

*** Error running after_component: C:\automatic1111\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py    Traceback (most recent call last):
      File "C:\automatic1111\modules\scripts.py", line 898, in after_component
        script.after_component(component, **kwargs)
      File "C:\automatic1111\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 111, in after_component
        toprow.add(self.enqueue_row)
    AttributeError: 'NoneType' object has no attribute 'add'

**Comment by hotwareboy** [comment]
Got it back up and working, not sure how.  Will keep testing.
