### ISSUE TITLE
*** Error loading script: task_scheduler.py | ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\typing_extensions.py)

### ISSUE THREAD

**Issue by zisonMyu** [ArtVentureX/sd-webui-agent-scheduler#215]
`*** Error loading script: task_scheduler.py
    Traceback (most recent call last):
      File "E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\extensions\agent-scheduler\scripts\task_scheduler.py", line 24, in <module>
        from agent_scheduler.task_runner import TaskRunner, get_instance
      File "E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\extensions\agent-scheduler\agent_scheduler\task_runner.py", line 26, in <module>
        from .db import TaskStatus, Task, task_manager
      File "E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\extensions\agent-scheduler\agent_scheduler\db\__init__.py", line 2, in <module>
        from sqlalchemy import create_engine, inspect, text, String, Text
      File "E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\sqlalchemy\__init__.py", line 12, in <module>
        from . import util as _util
      File "E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\sqlalchemy\util\__init__.py", line 15, in <module>
        from ._collections import coerce_generator_arg as coerce_generator_arg
      File "E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\sqlalchemy\util\_collections.py", line 38, in <module>
        from .typing import is_non_string_iterable
      File "E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\sqlalchemy\util\typing.py", line 56, in <module>
        from typing_extensions import TypeAliasType as TypeAliasType  # 3.12
    ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (E:\AI_stuff\A111-Webui\Webuis\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\typing_extensions.py)
`
When I migrated my A111 webui to a new computer, this issue caused the plugin to not work properly.
I reinstalled the entire webui and tried to upgrade typing_extensions, but the problem still occurs. How do I fix it?

**Comment by zisonMyu** [comment]
Problem solved, I just reinstall the entire venv.
However, Nothing happened when I clicked enqueue
