### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by theakiraproject** [ArtVentureX/sd-webui-agent-scheduler#23]
Not sure if it is just me, but just updated SD Automatic 1111 today, this is the error I am getting:

Error executing callback ui_tabs_callback for /Users/akira/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py
Traceback (most recent call last):
  File "/Users/local/stable-diffusion-webui/modules/script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "/Users/local/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py", line 337, in on_ui_tab
    selected_task.change(
  File "/Users/local/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/events.py", line 132, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "/Users/local/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 217, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "/Users/local/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 869, in check_function_inputs_match
    if not is_special_typed_parameter(name):
  File "/Users/local/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 858, in is_special_typed_parameter
    is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class

**Comment by artventuredev** [comment]
@theakiraproject I couldn't reproduce the issue on my end. After some debugging, I found that the line number in your error doesn't match mine, so I suspect that there are some differences in dependency versions. Could you please provide the exact version of the following dependencies: SD (commit), Python, and Gradio? You can find this information in the footer of the web UI. 

<img width="672" alt="Screenshot 2023-06-10 at 04 39 22" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/bd238a91-4558-4f21-8def-abe0a5c191d5">

<img width="803" alt="Screenshot 2023-06-10 at 04 32 41" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/8a89e884-1320-43ec-8d67-15ba66e29e16">

You can also try deleting the `venv` folder and let SD initialize it again.

**Comment by theakiraproject** [comment]
I tried deleting the venv folder, but it totally screwed up my installation and won't even boot up Automatic 1111 now. 

But, here are my version dependencies: 
python: 3.10.11  •  torch: 2.0.0  •  xformers: N/A  •  gradio: 3.28.1  •  commit: 5ab7f213  •  checkpoint: 0b914c246e

**Comment by theakiraproject** [comment]
Solved it by appending your gradio and torch versions in the requirements_versions.txt file
