### ISSUE TITLE
Using an invalid input image when using ControlNet.

### ISSUE THREAD

**Issue by critoc** [ArtVentureX/sd-webui-agent-scheduler#246]
When I use controlnet to register a task queue, the generated output is messed up because it uses a previously generated input image rather than the one I entered. I get an error saying that the ID is not found. I am on v1.8.0 and this error has been the same for both SDXL and SD1.5. 

This was fine before I updated ControlNet, so is there a problem? 

-------------------------
Exception deleting task from database: Task with id task(qoxp4fcwtyjl5t0) not found
*** API error: DELETE: http://127.0.0.1:7860/agent-scheduler/v1/task/task(qoxp4fcwtyjl5t0) {'error': 'Exception', 'detail': '', 'body': '', 'errors': 'Task with id task(qoxp4fcwtyjl5t0) not found'}
    Traceback (most recent call last):
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\modules\api\api.py", line 186, in exception_handling
        return await call_next(request)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\modules\api\api.py", line 150, in log_and_time
        res: Response = await call_next(req)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
        await self.simple_response(scope, receive, send, request_headers=headers)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
        await self.app(scope, receive, send)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\api.py", line 378, in delete_task
        task_manager.delete_task(id)
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\db\task.py", line 332, in delete_task
        raise e
      File "C:\Users\skyri\Desktop\AIart\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\db\task.py", line 329, in delete_task
        raise Exception(f"Task with id {id} not found")
    Exception: Task with id task(qoxp4fcwtyjl5t0) not found

**Comment by critoc** [comment]
After reinstalling the extension, the issue was resolved. I don't know why this happened.
