### ISSUE TITLE
Cannot use on webui forge

### ISSUE THREAD

**Issue by 777oxxo** [ArtVentureX/sd-webui-agent-scheduler#253]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\SdxlWebUi\setup\SdxlWebUi\venv-forge\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\SdxlWebUi\setup\SdxlWebUi\venv-forge\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\SdxlWebUi\setup\SdxlWebUi\venv-forge\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\SdxlWebUi\setup\SdxlWebUi\venv-forge\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\SdxlWebUi\setup\SdxlWebUi\venv-forge\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\SdxlWebUi\setup\SdxlWebUi\venv-forge\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\SdxlWebUi\setup\SdxlWebUi\venv-forge\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion-webui\SdxlWebUi\setup\SdxlWebUi\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 225, in f
    task_runner.register_ui_task(
AttributeError: 'NoneType' object has no attribute 'register_ui_task'

**Comment by coderCK2** [comment]
Piggybacking on this, though I'm getting a different error with Forge (latest version as of this comment):
```
Using sqlite file: D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\task_scheduler.sqlite3
*** Error loading script: task_scheduler.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 24, in <module>
        from agent_scheduler.task_runner import TaskRunner, get_instance
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 26, in <module>
        from .db import TaskStatus, Task, task_manager
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\agent_scheduler\db\__init__.py", line 6, in <module>
        from .task import TaskStatus, Task, TaskManager
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\agent_scheduler\db\task.py", line 22, in <module>
        from ..models import TaskModel
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\agent_scheduler\models.py", line 53, in <module>
        class Txt2ImgApiTaskArgs(StableDiffusionTxt2ImgProcessingAPI):
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\agent_scheduler\models.py", line 71, in Txt2ImgApiTaskArgs
        class Config(StableDiffusionTxt2ImgProcessingAPI.__config__):
      File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 237, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__
```

**Comment by tkizm1** [comment]
python -m pip install  pydantic==1.10.21
not work 
https://github.com/supersonic13/sd-webui-agent-scheduler.git

**Comment by mirh** [comment]
Alas that's broken too
https://github.com/supersonic13/sd-webui-agent-scheduler/issues/6
