### ISSUE TITLE
im getting error since today, done all updates and error still persists

### ISSUE THREAD

**Issue by dave8x** [ArtVentureX/sd-webui-agent-scheduler#255]
hi, yesterday was all working fine, and this morning i started getting an error when i try to add a schedule. be it txt2img or img2img. the normal generate works fine. 
I've now updated both A1111 gui and also all the extensions, but still getting error. 

> Traceback (most recent call last):
  File "C:\Users\lets_\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio

\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\lets_\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio

\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\lets_\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio

\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\lets_\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio

\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\lets_\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio

\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\lets_\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\anyio

\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\lets_\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio

\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\lets_\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\extensions\sd-webui-agent-scheduler

\scripts\task_scheduler.py", line 225, in f
    task_runner.register_ui_task(
  File "C:\Users\lets_\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\extensions\sd-webui-agent-scheduler

\agent_scheduler\task_runner.py", line 280, in register_ui_task
    (params, script_args) = self.__serialize_ui_task_args(
  File "C:\Users\lets_\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\extensions\sd-webui-agent-scheduler

\agent_scheduler\task_runner.py", line 124, in __serialize_ui_task_args
    params = json.dumps(
  File "json\__init__.py", line 231, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type _TemporaryFileWrapper is not JSON serializable

> 

any help highly appreciated (i'm not technical but i'll try my best to provide additional info if needed)
thanks in advance

**Comment by Xerophayze** [comment]
If you're running the forge edition of the automatic 1111 interface, they
recently pushed an update out that kind of broke parts of it or started
causing errors. I'm wondering if that may be what this is. I haven't pushed
the update yet myself, but a lot of people on my discord server have
brought it to our attention. You can try reinstalling the interface again
using stability matrix, and see if that helps. I know instability matrix,
when you go to install a package I believe you can select which branch you
might want to select the previous update and install that one.

**Comment by dave8x** [comment]
Hi thanks for quick reply. I dont know about forge edition. I am using stability matrix since it does everything on its own. I was using ver 1.9 of A1111 and was working fine (been using that for several months). then it stopped working. After it stopped working I tried updating it to ver 1.10 but still same issues. So if I understood you correctly I should try installing  ver 1.8? i will try it just in case and see how it goes

**Comment by Xerophayze** [comment]
I decided to try updating my Forge installation, which I use stability Matrix to manage it. And yes it seems to break the agent scheduler installation. Not sure if mine is similar, I have reduced the number of extensions down in my system to bare minimum. This is the trace back I'm getting:

Using sqlite file: H:\Personal\hobbies\AI-Art\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge2\extensions\sd-webui-agent-scheduler\task_scheduler.sqlite3
*** Error loading script: task_scheduler.py
    Traceback (most recent call last):
      File "H:\Personal\hobbies\AI-Art\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge2\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\Personal\hobbies\AI-Art\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge2\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\Personal\hobbies\AI-Art\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge2\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 24, in <module>
        from agent_scheduler.task_runner import TaskRunner, get_instance
      File "H:\Personal\hobbies\AI-Art\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge2\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 26, in <module>
        from .db import TaskStatus, Task, task_manager
      File "H:\Personal\hobbies\AI-Art\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge2\extensions\sd-webui-agent-scheduler\agent_scheduler\db\__init__.py", line 6, in <module>
        from .task import TaskStatus, Task, TaskManager
      File "H:\Personal\hobbies\AI-Art\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge2\extensions\sd-webui-agent-scheduler\agent_scheduler\db\task.py", line 22, in <module>
        from ..models import TaskModel
      File "H:\Personal\hobbies\AI-Art\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge2\extensions\sd-webui-agent-scheduler\agent_scheduler\models.py", line 53, in <module>
        class Txt2ImgApiTaskArgs(StableDiffusionTxt2ImgProcessingAPI):
      File "H:\Personal\hobbies\AI-Art\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge2\extensions\sd-webui-agent-scheduler\agent_scheduler\models.py", line 71, in Txt2ImgApiTaskArgs
        class Config(StableDiffusionTxt2ImgProcessingAPI.__config__):
      File "H:\Personal\hobbies\AI-Art\StabilityMatrix\Data\Packages\Stable Diffusion WebUI Forge2\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 237, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__ 

I keep it back up of my installation because I use it in a production environment. I'll be reverting back to that version. But it would be cool to get this updated because a lot of the updates that they're going to be pushing through Forge and through automatic 1111 are going to be geared towards the new flux model. I've created a complete front end that utilizes your extension to allow people to use my system to generate images. And I want to be able to give them access to the flux model eventually. Any help I can offer in this I would love to pitch in.

**Comment by itasky** [comment]
i just installed  it on FORGE and i get the same error. 

`*** Error loading script: task_scheduler.py
    Traceback (most recent call last):
      File "G:\forge\webui\modules\scripts.py", line 525, in load_scripts`

no error on Automatic1111

**Comment by coderCK2** [comment]
Same issue with Forge here:
```
*** Error loading script: task_scheduler.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\StableDiffusion\stable-diffusion-webui-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 24, in <module>
        from agent_scheduler.task_runner import TaskRunner, get_instance
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 26, in <module>
        from .db import TaskStatus, Task, task_manager
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\agent_scheduler\db\__init__.py", line 6, in <module>
        from .task import TaskStatus, Task, TaskManager
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\agent_scheduler\db\task.py", line 22, in <module>
        from ..models import TaskModel
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\agent_scheduler\models.py", line 53, in <module>
        class Txt2ImgApiTaskArgs(StableDiffusionTxt2ImgProcessingAPI):
      File "D:\StableDiffusion\stable-diffusion-webui-forge\extensions\sd-webui-agent-scheduler\agent_scheduler\models.py", line 71, in Txt2ImgApiTaskArgs
        class Config(StableDiffusionTxt2ImgProcessingAPI.__config__):
      File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 237, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__
```

**Comment by Xerophayze** [comment]
Yeah I believe if you're running an updated version of automatic 1111 or
Forge, the agent scheduler doesn't work. I was getting the same error. I
kept a backup of my forge install that I managed through stability matrix
and just use that one now. I have a separate install for the newer version
of Forge so I can mess around with flux.

**Comment by majocola** [comment]
Yes same Problem on Forge.ITs because of that new Skin that also supports FLUX.
I dont wanna miss FLUX at the moment.
Would be cool if the DEV here could make an updated Version for Forge.

**Comment by critoc** [comment]
The most stable version of agent scheduler is probably up to version 1.8.0. Hopefully this extension will be updated, I have a big problem with conflicts with Dynamic Prompt and scheduler changes.  It works partially in 1.9.0, but not completely, and I can't update to 1.10 because of this extension.

**Comment by dave8x** [comment]
> The most stable version of agent scheduler is probably up to version 1.8.0. Hopefully this extension will be updated, I have a big problem with conflicts with Dynamic Prompt and scheduler changes. It works partially in 1.9.0, but not completely, and I can't update to 1.10 because of this extension.

I do have dynamic prompt and scheduler but never had issues with 1.9. Whats wrong with yours at 1.9?

**Comment by critoc** [comment]
The dynamic prompt syntax (especially wildcards) did not work in some situations, such as when excessively increasing the batch size. I cannot reproduce the issue exactly. Additionally, there is an issue where the scheduler is not actually being changed. If you click on the queue registered in the agent scheduler, it always shows DPM++ 2M as the default, rather than the sampler you have set

**Comment by raffetazarius** [comment]
This issue looks like a dupe of https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/253
