### ISSUE TITLE
Extension no longer shows up in Forge

### ISSUE THREAD

**Issue by dronelove** [ArtVentureX/sd-webui-agent-scheduler#256]
Hi, it seems Agent Scheduler no longer works in Forge -- the extension tab and Enqueue button are gone. 

Currently running this version: https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/aadc0f04c48eb19475752a4206420ea2004e2f42

**Comment by EleVicted** [comment]
+1 , excellent extension too. Hopefully we can figure it out. I get this at startup:

Using sqlite file: /content/gdrive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/task_scheduler.sqlite3
*** Error loading script: task_scheduler.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py", line 24, in <module>
        from agent_scheduler.task_runner import TaskRunner, get_instance
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/agent_scheduler/task_runner.py", line 26, in <module>
        from .db import TaskStatus, Task, task_manager
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/agent_scheduler/db/__init__.py", line 6, in <module>
        from .task import TaskStatus, Task, TaskManager
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/agent_scheduler/db/task.py", line 22, in <module>
        from ..models import TaskModel
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/agent_scheduler/models.py", line 53, in <module>
        class Txt2ImgApiTaskArgs(StableDiffusionTxt2ImgProcessingAPI):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui-forge/extensions/sd-webui-agent-scheduler/agent_scheduler/models.py", line 71, in Txt2ImgApiTaskArgs
        class Config(StableDiffusionTxt2ImgProcessingAPI.__config__):
      File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 237, in __getattr__
        raise AttributeError(item)
    AttributeError: __config__

---

**Comment by kyle215ps3** [comment]
> Hi, it seems Agent Scheduler no longer works in Forge -- the extension tab and Enqueue button are gone.
> 
> Currently running this version: [lllyasviel/stable-diffusion-webui-forge@aadc0f0](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/aadc0f04c48eb19475752a4206420ea2004e2f42)

probably because of Gradio 4.0 update

**Comment by Miuna88** [comment]
I haven't updated forge recently and the extension has stopped working there too. It does still appear in the UI but pressing the "enqueue" button doesn't do anything - worked fine up until maybe a day or two ago. Weird how base queue systems aren't included in GUI's at this point considering its such a useful tool.

**Comment by dronelove** [comment]
Could be your history database got too big. Try deleting the sqlite3
history file (it’s in the extension’s directory).

**Comment by younyokel** [comment]
Forge needs a good built-in queue system.

**Comment by cuom1705** [comment]
same here. I hope that we get update soon to use with forge

**Comment by gohan2091** [comment]
I would like to get this working in Forge also

**Comment by supersonic13** [comment]
ok - I got it working - but barely. Forked this repo and fixed a few issues:
https://github.com/supersonic13/sd-webui-agent-scheduler

Caveats: Forge now does not automatically load a model - so this breaks the agent scheduler. Only workaround is to generate manually first and then the enqueue should work. I haven’t tested a lot but this patch is not perfect but hope to sort out the issues over the next few days and hopefully submit a pull request to this repo. 

Submitted a pull request but deleted as it was a half baked approach (disclaimer: first time figuring out Gradio etc)

**Comment by Mark-Reiser** [comment]
I too think this extension should be embedded by default into Forge. pleeeeease!

**Comment by raffetazarius** [comment]
This issue looks like a dupe of https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/253

**Comment by hendra2222** [comment]
> ok - I got it working - but barely. Forked this repo and fixed a few issues: https://github.com/supersonic13/sd-webui-agent-scheduler
> 
> Caveats: Forge now does not automatically load a model - so this breaks the agent scheduler. Only workaround is to generate manually first and then the enqueue should work. I haven’t tested a lot but this patch is not perfect but hope to sort out the issues over the next few days and hopefully submit a pull request to this repo.
> 
> Submitted a pull request but deleted as it was a half baked approach (disclaimer: first time figuring out Gradio etc)

Well done, I've deployed this for try out, all the button is there 

> ok - I got it working - but barely. Forked this repo and fixed a few issues: https://github.com/supersonic13/sd-webui-agent-scheduler
> 
> Caveats: Forge now does not automatically load a model - so this breaks the agent scheduler. Only workaround is to generate manually first and then the enqueue should work. I haven’t tested a lot but this patch is not perfect but hope to sort out the issues over the next few days and hopefully submit a pull request to this repo.
> 
> Submitted a pull request but deleted as it was a half baked approach (disclaimer: first time figuring out Gradio etc)

I've tried this, all the buttons is there but nothing happend when I press enqueue.

**Comment by supersonic13** [comment]
Hi - yes so you need to "generate" first - and only then the enqueue would work with future generations. This is because of the way Forge has been re-written, where it does not auto load models/checkpoints. 

I am hoping to find some time this week to fix the Enqueue button action so it starts working as soon as it is clicked.

**Comment by hendra2222** [comment]
> Hi - yes so you need to "generate" first - and only then the enqueue would work with future generations. This is because of the way Forge has been re-written, where it does not auto load models/checkpoints.
> 
> I am hoping to find some time this week to fix the Enqueue button action so it starts working as soon as it is clicked.

oh wowwww! thank you for the effort! I will try this ^^

**Comment by hendra2222** [comment]
> Hi - yes so you need to "generate" first - and only then the enqueue would work with future generations. This is because of the way Forge has been re-written, where it does not auto load models/checkpoints.
> 
> I am hoping to find some time this week to fix the Enqueue button action so it starts working as soon as it is clicked.

Hi, 
First of all thank you so much for the effort! I played around with it today and yeah it kind of works. But when using multiple models for different queues this one dont work. 
For example model1 for queue 1 with xxx prompt then model2 for queue 2 with xxx prompt. The prompt is there but the model doesnt changed ^^

**Comment by cupofwater1** [comment]
> Hi - yes so you need to "generate" first - and only then the enqueue would work with future generations. This is because of the way Forge has been re-written, where it does not auto load models/checkpoints.
> 
> I am hoping to find some time this week to fix the Enqueue button action so it starts working as soon as it is clicked.

Hey wanted to say thank you for taking the time to make this, this extension is so helpful and very convenient to use so again I'm glad you are importing this to forge. But for me, I did do this and it still doesn't work unfortunately, I allow a photo to be generated then after it is generated, i click on enqueue but nothing shows in the agent scheduler tab. Is there anything that I'm doing wrong? 
![image](https://github.com/user-attachments/assets/4342b149-b1a5-448e-a882-7f48c7a3057f)
![image](https://github.com/user-attachments/assets/e23bb9f1-ce8e-4432-bd02-e29a7a7177c7)

**Comment by brknsoul** [comment]
Yeah, @supersonic13 's fork doesn't work anymore, even after genning first.

**Comment by coderCK2** [comment]
> Yeah, @supersonic13 's fork doesn't work anymore, even after genning first.

There was a Forge update recently that makes the fork no longer work. Since I only really experiment with Flux and don't any new features, I just revert to an old commit and use the non-forked version of the scheduler, and everything works just fine again.

**Comment by cupofwater1** [comment]
> > Yeah, @supersonic13 's fork doesn't work anymore, even after genning first.
> 
> There was a Forge update recently that makes the fork no longer work. Since I only really experiment with Flux and don't any new features, I just revert to an old commit and use the non-forked version of the scheduler, and everything works just fine again.

Which one did you use?

**Comment by coderCK2** [comment]
> Which one did you use?

I am a little bit perplexed, as I had been using a very old commit (https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7) and wanted to provide you with a newer one, as well as perhaps pinpoint the recent commit that broke the Enqueue button; unfortunately (fortunately?) I could not find it! Every commit I tested worked just fine, including the most recent commit, https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/f4d5e8cac16a42fa939e78a0956b4c30e2b47bb5. With that commit and the forked version of the scheduler, I can schedule jobs just fine (I only tested queuing jobs after generating once). 🤷🏻‍♂️

**Comment by cupofwater1** [comment]
> > Which one did you use?
> 
> I am a little bit perplexed, as I had been using a very old commit ([lllyasviel/stable-diffusion-webui-forge@29be1da](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7)) and wanted to provide you with a newer one, as well as perhaps pinpoint the recent commit that broke the Enqueue button; unfortunately (fortunately?) I could not find it! Every commit I tested worked just fine, including the most recent commit, [lllyasviel/stable-diffusion-webui-forge@f4d5e8c](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/f4d5e8cac16a42fa939e78a0956b4c30e2b47bb5). With that commit and the forked version of the scheduler, I can schedule jobs just fine (I only tested queuing jobs after generating once). 🤷🏻‍♂️
> 
> EDIT: Okay this is strange. After doing some more generations on the latest commit, the Enqueue button stopped working at some point. Apparently it's not broken from the start, which is why my tests of doing one generation and then running a job kept working. I don't have any more time to figure out which commit causes this behavior, but if you want a working old version with no Flux support, switch to the [first commit I mentioned](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7), and be sure to also switch to the non-forked scheduler.

Oh yeah, unfortunately I need one what works with Flux

**Comment by coderCK2** [comment]
> Oh yeah, unfortunately I need one what works with Flux

If you have time, you can try some older commits. I can tell you for a fact that commit https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/c2d290e6c92345145c79ed24a3f5c2fd56fd81d7 is the first one where I noticed the Enqueue button was broken, so commits prior to that would be a good starting point.

**Comment by supersonic13** [comment]
@hendra2222 @cupofwater1 pushed some changes to the fork:
https://github.com/supersonic13/sd-webui-agent-scheduler

I'm now able to enqueue straight away (without needing to generate first) and it all seems to work for me.
However, the queued tasks end up using the main checkpoint selected in the top bar.
Hoping to find more time to solve this. (feel it's very close, though there are tons of complaints on the Forge forums about the inability to choose checkpoints on the go - so maybe not as close to a complete solution as I think) but please do let me know here if it's still badly broken and I'll probably do a fresh install, etc, and try it out.

**Comment by brknsoul** [comment]
While it seems to function on the main Forge fork, it doesn't function on lshqqytiger's amdgpu fork; https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge

Created issue there.
https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge/issues/40

**Comment by brknsoul** [comment]
While the elements (Enqueue button, AS tab) show up, the Enqueue button still does nothing.

Tested on commits [953e3f3](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/953e3f39833d9de742223be882b86c5be0efaa1c) and [2d3903db](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/2d3903db6873f418a48476cba3b0b226be1970fa).

**Comment by supersonic13** [comment]
@brknsoul hello. i'll try to do a clean install and test it out again. are there any console logs that show up when the Enqueue button is clicked ?

**Comment by brknsoul** [comment]
Okay, it works, but only after I refresh the tab (Chrome, Windows 10). Might be a Chrome Thing ™ ;-)

**Comment by 5n0wCr45h** [comment]
So I think on first launch the Generate button isn't set, therefore the Enqueue button cannot be bound:

ERROR:root:Generate button not set; cannot bind enqueue button.

But after the Generate button is used once it is set, then if the browser tab is refreshed the Enqueue button can bind...but I have no idea how to fix that :(

**Comment by supersonic13** [comment]
@5n0wCr45h thanks for the logs. i can add some code to bind the button after a couple of more IDs are set.

**Comment by supersonic13** [comment]
> Any success?

Hello. I tried to reproduce this on my PC but couldn't. I have added another check in the code, in any case. Can you update the forked extension and try it out please ?

**Comment by 5n0wCr45h** [comment]
I should have time to try it tomorrow and will post the results.

**Comment by 5n0wCr45h** [comment]
Initial testing looks promising.

**Comment by 5n0wCr45h** [comment]
:( sorry, second test and same thing, must press the generation button first, reload the tab, then Enqueue works.

**Comment by supersonic13** [comment]
> :( sorry, second test and same thing, must press the generation button first, reload the tab, then Enqueue works.

That's not great. Would it be possible to provide any console logs you might have when that happens please ?

**Comment by 5n0wCr45h** [comment]
Sorry, it will me a while before I can put time into this :(

**Comment by younyokel** [comment]
@supersonic13 I don't expect updates to this repository, so If you're interested in continuing development, could you consider opening issues in your fork?

**Comment by supersonic13** [comment]
> @supersonic13 I don't expect updates to this repository, so If you're interested in continuing development, could you consider opening issues in your fork?

hi sure .. I've just updated the repo to include Issues .. Obviously, any PRs are also welcome ..

**Comment by zzrjuan** [comment]
> ok - I got it working - but barely. Forked this repo and fixed a few issues: https://github.com/supersonic13/sd-webui-agent-scheduler
> 
> Caveats: Forge now does not automatically load a model - so this breaks the agent scheduler. Only workaround is to generate manually first and then the enqueue should work. I haven’t tested a lot but this patch is not perfect but hope to sort out the issues over the next few days and hopefully submit a pull request to this repo.
> 
> Submitted a pull request but deleted as it was a half baked approach (disclaimer: first time figuring out Gradio etc)

this  can change checkpoint
https://github.com/htmambo/sd-webui-agent-scheduler

**Comment by raffetazarius** [comment]
@zzrjuan - does https://github.com/htmambo/sd-webui-agent-scheduler work with Forge?

@supersonic13 - does https://github.com/supersonic13/sd-webui-agent-scheduler work with Forge?

Thanks!

**Comment by younyokel** [comment]
> [@zzrjuan](https://github.com/zzrjuan) - does https://github.com/htmambo/sd-webui-agent-scheduler work with Forge?
> 
> [@supersonic13](https://github.com/supersonic13) - does https://github.com/supersonic13/sd-webui-agent-scheduler work with Forge?
> 
> Thanks!

yes

**Comment by raffetazarius** [comment]
> > [@zzrjuan](https://github.com/zzrjuan) - does https://github.com/htmambo/sd-webui-agent-scheduler work with Forge?
> > [@supersonic13](https://github.com/supersonic13) - does https://github.com/supersonic13/sd-webui-agent-scheduler work with Forge?
> > Thanks!
> 
> yes

LOL. @younyokel - _both_ work with Forge?  Or which one were you referring to that does work?

**Comment by Mark-Reiser** [comment]
@supersonic13 Can you please give a us hint here when you have your next update ready so it works better with Forge?

**Comment by ZeroCool1977** [comment]
well now i know why i couldn't find it after install in forge. bummer!

**Comment by rktvr** [comment]
also doesn't work with reforge
