### ISSUE TITLE
[Feature] Support sd-webui-IS-NET-pro script

### ISSUE THREAD

**Issue by tim9292654** [ArtVentureX/sd-webui-agent-scheduler#40]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await [anyio.to](http://anyio.to/)_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 198, in f
    task_runner.register_ui_task(
  File "D:\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 211, in register_ui_task
    params = self.__serialize_ui_task_args(is_img2img, *args, checkpoint=checkpoint)
  File "D:\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 120, in __serialize_ui_task_args
    return json.dumps(
  File "C:\Users\4\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\4\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\4\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\4\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable

**Comment by artventuredev** [comment]
What are your installed extensions?

**Comment by tim9292654** [comment]
> What are your installed extensions?已安装的扩展是什么？

The sd-webui-IS-NET-pro extension conflicts with the sd-webui-agent-scheduler extension.

**Comment by artventuredev** [comment]
Extension `sd-webui-IS-NET-pro` is not supported yet. I'll add to the backlog. But I'm super busy with my day job right now, so it's gonna take a while before I can get to it.

**Comment by tim9292654** [comment]
Error executing callback app_started_callback for D:\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\script_callbacks.py", line 125, in app_started_callback
    c.callback(demo, app)
  File "D:\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 66, in <lambda>
    script_callbacks.on_app_started(lambda block, _: self.on_app_started(block))
  File "D:\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 105, in on_app_started
    self.bind_enqueue_button(block)
  File "D:\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 174, in bind_enqueue_button
    self.submit_button.click(**args)
AttributeError: 'NoneType' object has no attribute 'click'

**Comment by artventuredev** [comment]
The same as https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/51, should be fixed already.

**Comment by artventuredev** [comment]
@tim9292654 You may want to try the latest version, the `sd-webui-IS-NET-pro` extension should work now.
