### ISSUE TITLE
Doesn't work with Ultimate SD Upscale

### ISSUE THREAD

**Issue by acoolrocket** [ArtVentureX/sd-webui-agent-scheduler#49]
Getting this error:

```
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\ai\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 201, in f
    task_runner.register_ui_task(
  File "C:\ai\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 211, in register_ui_task
    params = self.__serialize_ui_task_args(is_img2img, *args, checkpoint=checkpoint)
  File "C:\ai\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 120, in __serialize_ui_task_args
    return json.dumps(
  File "C:\Users\Acoolrocket\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Acoolrocket\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Acoolrocket\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Acoolrocket\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ControlNetUnit is not JSON serializable

```

Doesn't appear on queue list.

**Comment by artventuredev** [comment]
I'm able to queue a task with `Ultimate SD Upscale` and `ControlNet` on my end and the task run just fine. 
Are there any other always on scripts that you're using? They should be listed right above the script section like this:

<img width="739" alt="Screenshot 2023-06-27 at 00 30 32" src="https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/f8b8c127-c47c-484e-942e-ad49dc6ca331">

**Comment by acoolrocket** [comment]
Nothing else, just using img2img and Ultimate SD upscale.

Also tried on my second PC that has the same extensions and same exact error in CMD.

![image](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/61209177/da273fb6-b4c3-4828-b0cd-69bbe34ff081)

**Comment by artventuredev** [comment]
@acoolrocket Your controlnet is too old already, please update the controlnet extension and try again.

**Comment by acoolrocket** [comment]
Updating the extensions actually fixed it, thanks a bunch, working now as expected!
