### ISSUE TITLE
Error when start up stable Diffusion

### ISSUE THREAD

**Issue by SauChi666** [ArtVentureX/sd-webui-agent-scheduler#51]
Error executing callback app_started_callback for /Users/appleid/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py
Traceback (most recent call last):
  File "/Users/appleid/stable-diffusion-webui/modules/script_callbacks.py", line 125, in app_started_callback
    c.callback(demo, app)
  File "/Users/appleid/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py", line 66, in <lambda>
    script_callbacks.on_app_started(lambda block, _: self.on_app_started(block))
  File "/Users/appleid/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py", line 105, in on_app_started
    self.bind_enqueue_button(block)
  File "/Users/appleid/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py", line 174, in bind_enqueue_button
    self.submit_button.click(**args)
AttributeError: 'NoneType' object has no attribute 'click'

Error executing callback app_started_callback for /Users/appleid/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py
Traceback (most recent call last):
  File "/Users/appleid/stable-diffusion-webui/modules/script_callbacks.py", line 125, in app_started_callback
    c.callback(demo, app)
  File "/Users/appleid/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py", line 66, in <lambda>
    script_callbacks.on_app_started(lambda block, _: self.on_app_started(block))
  File "/Users/appleid/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py", line 105, in on_app_started
    self.bind_enqueue_button(block)
  File "/Users/appleid/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/scripts/task_scheduler.py", line 174, in bind_enqueue_button
    self.submit_button.click(**args)
AttributeError: 'NoneType' object has no attribute 'click'

Startup time: 12.3s (import torch: 0.7s, import gradio: 0.6s, import ldm: 0.2s, other imports: 0.6s, setup codeformer: 0.1s, load scripts: 4.1s, create ui: 5.2s, gradio launch: 0.4s, scripts app_started_callback: 0.3s).

**Comment by artventuredev** [comment]
Please provide your webui version? You can find the version info at the bottom of the web page.

![Screenshot 2023-06-27 at 12 56 14](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/133728487/49c47318-1a1c-4a27-83aa-4b475f3470b8)

**Comment by deepfree3** [comment]
Same error. version: [v1.3.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0)  •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.19  •  gradio: 3.32.0

AttributeError: 'Options' object has no attribute 'queue_button_placement'
AttributeError: 'NoneType' object has no attribute 'click'

**Comment by artventuredev** [comment]
I just update a fix, please try the latest commit.

**Comment by deepfree3** [comment]
No AttributeError now. But nothing happens after pressing enqueue button.

**Comment by artventuredev** [comment]
Then you can check this: https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/4#issuecomment-1575986274

**Comment by deepfree3** [comment]
Thanks, it's OK now.

**Comment by SauChi666** [comment]
THX!
