### ISSUE TITLE
[Feature] Add support for adetailer extension

### ISSUE THREAD

**Issue by brknsoul** [ArtVentureX/sd-webui-agent-scheduler#62]
This seems to be a issue that was solved before (https://github.com/ArtVentureX/sd-webui-agent-scheduler/issues/59) and now has re-appeared;

```
Traceback (most recent call last):
  File "E:\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 210, in f
    task_runner.register_ui_task(
  File "E:\automatic\extensions-builtin\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 215, in register_ui_task
    params = self.__serialize_ui_task_args(is_img2img, *args, checkpoint=checkpoint)
  File "E:\automatic\extensions-builtin\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 123, in __serialize_ui_task_args
    return json.dumps(
  File "C:\Program Files\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type object is not JSON serializable
```

```
Starting [SD.Next](https://github.com/vladmandic/automatic)
Python 3.10.11 on Windows
Version: 875d0db1 Sun Jul 2 08:26:51 2023 -0400
Updating main repository
Upgraded to version: 45d50bd1 Wed Jul 5 00:12:07 2023 +0300
Using DirectML Backend
Torch 2.0.0+cpu
Torch backend: DirectML (torch-directml 0.2.0.dev230426)
Torch detected GPU: AMD Radeon RX 6600 XT
```

Using Agent Scheduler commit [75ba093](https://github.com/ArtVentureX/sd-webui-agent-scheduler/commit/75ba093d46b37f2d01fa4207680a4fa6417b01c3)

**Comment by artventuredev** [comment]
This is a different issue with a different extension. Please try to enqueue with one of your extension at a time to identity the not compatible one.

**Comment by brknsoul** [comment]
Yup, you were right, it was a1111-sd-webui-tagcomplete. I'll raise an issue with them.

**Comment by artventuredev** [comment]
Hmm I think it's not their issue. I just want to spot the not compatible one to see if I can add support to it. Can you also post the list of the installed extensions?

**Comment by brknsoul** [comment]
It started working when I disabled tagcomplete.. o.O

**Comment by artventuredev** [comment]
Try re-enable it and queue the exact config with your last success.

**Comment by brknsoul** [comment]
Ok, it seems it's aDetailer. https://github.com/Bing-su/adetailer

**Comment by artventuredev** [comment]
It should be me adding the support for the extension. Let me see if I can do anything.

**Comment by Bing-su** [comment]
This is because I added an argument that is not Json serialized.

https://github.com/Bing-su/adetailer/blob/57106db2b1146d82d981d951254d21a71076ab86/adetailer/ui.py#L43-L47
```py
def on_generate_click(state: dict, *values: Any):
    for attr, value in zip(ALL_ARGS.attrs, values):
        state[attr] = value
    state["is_api"] = object()  <--
    return state
```

You can fix this by simply adding an exception for it, but I would also recommend switching to a pickle-based database like [shelve](https://docs.python.org/3/library/shelve.html) or [diskcache](https://github.com/grantjenks/python-diskcache).

**Comment by artventuredev** [comment]
I actually gave the pickle method a shot before settling on JSON. The problem was that some extensions, like `controlnet`, store their values as class instances, and when I tried to unpickle them, it threw errors because the required class wasn't available in the script import path.

**Comment by artventuredev** [comment]
This issue should be fixed with [this update](https://github.com/Bing-su/adetailer/commit/44da346513e9374c37c6051c6e9f8dd6a7f45d00) from aDetailer.
