### ISSUE TITLE
AttributeError: 'int' object has no attribute 'username'

### ISSUE THREAD

**Issue by CptGabok** [ArtVentureX/sd-webui-agent-scheduler#65]
When I try to add an image to the queue, this is what I get...any ideas?

```
serialize sampler index: 0 as Euler a
[AgentScheduler] Total pending tasks: 1
[AgentScheduler] Executing task task(98m5all1djh9vj5)
*** Error completing request
*** Arguments: ('task(98m5all1djh9vj5)', 'test', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', ['Model hash: deliberate_v2.safetensors [9aba26abdf]'], 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', {'enabled': False, 'module': 'none', 'model': 'None', 'weight': 1.0, 'image': None, 'resize_mode': 'Crop and Resize', 'low_vram': False, 'processor_res': -1, 'threshold_a': -1, 'threshold_b': -1, 'guidance_start': 0.0, 'guidance_end': 1.0, 'pixel_perfect': False, 'control_mode': 'Balanced', 'is_ui': True, 'input_mode': 'simple', 'batch_images': None, 'output_dir': '', 'loopback': False, 'is_cnet': True}, {'enabled': False, 'module': 'none', 'model': 'None', 'weight': 1.0, 'image': None, 'resize_mode': 'Crop and Resize', 'low_vram': False, 'processor_res': -1, 'threshold_a': -1, 'threshold_b': -1, 'guidance_start': 0.0, 'guidance_end': 1.0, 'pixel_perfect': False, 'control_mode': 'Balanced', 'is_ui': True, 'input_mode': 'simple', 'batch_images': None, 'output_dir': '', 'loopback': False, 'is_cnet': True}, {'enabled': False, 'module': 'none', 'model': 'None', 'weight': 1, 'image': None, 'resize_mode': 'Crop and Resize', 'low_vram': False, 'processor_res': -1, 'threshold_a': -1, 'threshold_b': -1, 'guidance_start': 0, 'guidance_end': 1, 'pixel_perfect': False, 'control_mode': 'Balanced', 'is_ui': True, 'input_mode': 'simple', 'batch_images': '', 'output_dir': '', 'loopback': False, 'is_cnet': True}, 1, '', 0, '', True, False, False, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "stable-diffusion-webui\modules\txt2img.py", line 51, in txt2img
        p.user = request.username
    AttributeError: 'int' object has no attribute 'username'

---
<agent_scheduler.helpers.Log object at 0x000001652A6FC310> [AgentScheduler] Task task(98m5all1djh9vj5) failed:
NoneType: None

[AgentScheduler] Task queue is empty
```

**Comment by artventuredev** [comment]
What's your SD webui version/commit hash? Look like is already outdated, please update the webui and try again.

**Comment by CptGabok** [comment]
Looks like that fixed it, thanks!
