### ISSUE TITLE
Latest update broke Stable Diffusion

### ISSUE THREAD

**Issue by DaveyBoy1970** [ArtVentureX/sd-webui-agent-scheduler#76]
I've been using the extension just fine up until now - and I love it. But yesterday I noticed I was behind with my version and so I updated and then immediately I went to apply and restart UI, SD just completely broke. Below is the output now I start webui after the Agent Scheduler update. I have a very minimal Windows installation as I'm running it on only 2GB vram (which is why the scheduler is *so* useful!). I did try to reinstall SD but I've hit other problems.

```
venv "D:\AI\stable-diffusion-webui-old\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81

Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui-old\launch.py", line 356, in <module>
    start()
  File "D:\AI\stable-diffusion-webui-old\launch.py", line 351, in start
    webui.webui()
  File "D:\AI\stable-diffusion-webui-old\webui.py", line 243, in webui
    shared.demo = modules.ui.create_ui()
  File "D:\AI\stable-diffusion-webui-old\modules\ui.py", line 1474, in create_ui
    component = create_setting_component(k)
  File "D:\AI\stable-diffusion-webui-old\modules\ui.py", line 1391, in create_setting_component
    res = comp(label=info.label, value=fun(), elem_id=elem_id, **(args or {}))
  File "D:\AI\stable-diffusion-webui-old\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 482, in enqueue_keyboard_shortcut_ui
    modifiers.change(
  File "D:\AI\stable-diffusion-webui-old\venv\lib\site-packages\gradio\events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "D:\AI\stable-diffusion-webui-old\venv\lib\site-packages\gradio\blocks.py", line 195, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "D:\AI\stable-diffusion-webui-old\venv\lib\site-packages\gradio\utils.py", line 940, in check_function_inputs_match
    if not is_special_typed_parameter(name):
  File "D:\AI\stable-diffusion-webui-old\venv\lib\site-packages\gradio\utils.py", line 929, in is_special_typed_parameter
    is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class
Press any key to continue . . .
```

```

**Comment by artventuredev** [comment]
This is fixed on the latest commit. But your SD webui version is also quite outdated, please consider update it too, the extension may not working properly.

**Comment by DaveyBoy1970** [comment]
Thank you!

I am new to SD and only installed it a few weeks ago - I guess I must have followed an old tutorial. I did try to do a fresh install SD 1.5 but it all went horribly wrong and I don't know what mistake I made. Anyway, at least I have my working set up back thanks to you :-D
