### ISSUE TITLE
TypeError: Object of type DataFrame is not JSON serializable

### ISSUE THREAD

**Issue by jasoncow007** [ArtVentureX/sd-webui-agent-scheduler#77]
is this issue associate with gradio version？

log is as bellow,,,
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd-webui-aki-v4\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 211, in f
    task_runner.register_ui_task(
  File "D:\sd-webui-aki-v4\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 222, in register_ui_task
    params = self.__serialize_ui_task_args(is_img2img, *args, checkpoint=checkpoint)
  File "D:\sd-webui-aki-v4\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 127, in __serialize_ui_task_args
    raise e
  File "D:\sd-webui-aki-v4\extensions\sd-webui-agent-scheduler\agent_scheduler\task_runner.py", line 124, in __serialize_ui_task_args
    json.dumps(args)
  File "json\__init__.py", line 231, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type DataFrame is not JSON serializable

**Comment by artventuredev** [comment]
Please to the latest commit, the issue should be fixed.
