### ISSUE TITLE
Broken in 1.5.0RC

### ISSUE THREAD

**Issue by SLAPaper** [ArtVentureX/sd-webui-agent-scheduler#87]
```
[AgentScheduler] Total pending tasks: 1
[AgentScheduler] Executing task task(b7an306fnx7jwqr)
*** Error completing request
*** Arguments: ('task(b7an306fnx7jwqr)', '1girl', '', [], 50, 2, False, False, 1, 4, 8, 56.0, -1.0, 0, 0, 0, False, 768, 512, False, 0.4, 2, '4x-UltraMix_Balanced', 15, 0, 0, 0, '', '', ['Clip skip: 1', 'Model hash: test\\ARegularDeepBackground_v10.safetensors [d4620223b4]'], 0, 0, False, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, True, 1024, 96, True, True, True, True, False, 8, 100, 'Constant', 0, 'Half Cosine Up', 5, 4, {'enabled': False, 'module': 'depth_midas', 'model': 'control_v11f1p_sd15_depth [cfd03158]', 'weight': 1, 'image': None, 'resize_mode': 'Crop and Resize', 'low_vram': False, 'processor_res': 64, 'threshold_a': 64, 'threshold_b': 64, 'guidance_start': 0, 'guidance_end': 1, 'pixel_perfect': True, 'control_mode': 'Balanced', 'is_ui': True, 'input_mode': <InputMode.SIMPLE: 'simple'>, 'batch_images': '', 'output_dir': '', 'loopback': False}, {'enabled': False, 'module': 'none', 'model': 'None', 'weight': 1.0, 'image': None, 'resize_mode': <ResizeMode.INNER_FIT: 'Crop and Resize'>, 'low_vram': False, 'processor_res': -1, 'threshold_a': -1, 'threshold_b': -1, 'guidance_start': 0.0, 'guidance_end': 1.0, 'pixel_perfect': False, 'control_mode': <ControlMode.BALANCED: 'Balanced'>, 'is_ui': True, 'input_mode': <InputMode.SIMPLE: 'simple'>, 'batch_images': None, 'output_dir': '', 'loopback': False}, {'enabled': False, 'module': 'none', 'model': 'None', 'weight': 1, 'image': None, 'resize_mode': 'Crop and Resize', 'low_vram': False, 'processor_res': 64, 'threshold_a': 64, 'threshold_b': 64, 'guidance_start': 0, 'guidance_end': 1, 'pixel_perfect': False, 'control_mode': 'Balanced', 'is_ui': True, 'input_mode': <InputMode.SIMPLE: 'simple'>, 'batch_images': '', 'output_dir': '', 'loopback': False}, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL26:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nDEEPOFF:1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,1,1,1,1,1,1,1,1,1\nDEEPAMP:1,1,1,1,1,1,1,1,1,1,2,2,2,1,2,2,2,1,1,1,1,1,1,1,1,1', False, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, True, 0.75, 1, False, True, 9, 1, '', False, False, False, False, 'Auto', 0.5, 1, False, False, False, False, 'positive', 'comma', 0, False, False, '', 10, '', ['test\\ARegularDeepBackground_v10.safetensors', 'test\\bacchus_v31real.safetensors', 'test\\chibi3D_v15.safetensors', 'test\\cleanCartoonStyle_v10.safetensors', 'test\\crystalmix_10.safetensors', 'test\\dmfinale_v10.safetensors', 'test\\eighththing_v10.safetensors', 'test\\eighththing_v20.safetensors', 'test\\eighththing_v30.safetensors', 'test\\eighththing_v31.safetensors'], 6, '3,8,13', [], 0, '', [], True, False, False, False, 12, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', 'all', 'all', 'all', 'all', False, True, False, True, True, 'Create in UI', False, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', None, None, False, None, None, False, None, None, False, 50, '{inspiration}', None, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL26:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nDEEPOFF:1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,0,1,1,1,1,1,1,1,1,1\nDEEPAMP:1,1,1,1,1,1,1,1,1,1,2,2,2,1,2,2,2,1,1,1,1,1,1,1,1,1', False, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False) {}
    Traceback (most recent call last):
      File "C:\Users\SLAPaper\workspace\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\SLAPaper\workspace\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
        p.user = request.username
    AttributeError: 'int' object has no attribute 'username'

---
[AgentScheduler] Task task(b7an306fnx7jwqr) failed:
[AgentScheduler] Task queue is empty
```

**Comment by artventuredev** [comment]
Should be fixed in the last commit, please give it a try.

**Comment by aetherwu** [comment]
It works now.
